FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/cycler ./cmd/cycler

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/cycler /cycler
USER nonroot:nonroot
ENTRYPOINT ["/cycler"]
